// swift-tools-version: 6.0
import PackageDescription

// macOS 26 is the floor on purpose. This is a personal build for one machine
// (Darwin 25.6 / macOS 26.6), so there is no reason to carry the compat shims
// the upstream project needed to support macOS 14: no hand-rolled outside-click
// monitor, no NSHostingView workarounds, native MenuBarExtra and SwiftData only.
let package = Package(
    name: "PokeBar",
    platforms: [.macOS("26.0")],
    targets: [
        .executableTarget(
            name: "PokeBar",
            path: "Sources/PokeBar",
            // The Pokedex is a build-time manifest, generated by
            // scripts/generate-dex.py and checked in, rather than fetched from
            // PokeAPI at runtime. A cold first launch then needs no network and
            // no third-party service to be up, and the generator asserts the
            // invariants (1,083 entries, 58 regional forms, 14 static-only) that
            // a runtime fetch could only hope for. See DECISIONS.md.
            //
            // This makes SwiftPM emit PokeBar_PokeBar.bundle next to the binary,
            // which scripts/bundle.sh must copy into Contents/Resources or
            // Bundle.module finds nothing at runtime.
            resources: [.copy("Dex/Resources/pokedex.json")],
            swiftSettings: [
                // Surface data races at compile time rather than as the
                // generation-counter whack-a-mole the upstream defect log records.
                .swiftLanguageMode(.v6),
            ]
            // No sqlite3 link: both Claude Code and current Codex usage are
            // append-only JSONL. Cursor, Copilot and Kiro remain out of scope.
        ),
        .testTarget(
            name: "PokeBarTests",
            dependencies: ["PokeBar"],
            path: "Tests/PokeBarTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
