import Foundation

/// Which of the three sprite sets an entry's art comes from.
///
/// Resolution order is gen5 -> showdown -> home, decided at manifest-generation
/// time and recorded per entry so the app never probes for a 404. Prefers
/// authentic Black/White pixel art where it exists, falls back to Showdown's
/// unified animated set, then to static HOME renders for the last 14. Measured:
/// 816 entries via gen5, 253 via showdown, 14 via home.
enum SpriteSet: String, Codable, Sendable, CaseIterable {
    case gen5
    case showdown
    case home

    /// Only `home` is a still image. 1,069 of 1,083 entries animate.
    var isAnimated: Bool { self != .home }

    /// Path segment under `sprites/pokemon/`, without the filename.
    var directory: String {
        switch self {
        case .gen5: "versions/generation-v/black-white/animated"
        case .showdown: "other/showdown"
        case .home: "other/home"
        }
    }

    /// Derived from the set, deliberately, rather than carried per entry in the
    /// manifest. One source of truth: an entry cannot claim `home` and `.gif`.
    var fileExtension: String { self == .home ? "png" : "gif" }
}

/// Display rarity band, derived at generation time from the species'
/// `capture_rate`.
///
/// This is a *label*, not a weighting axis. `capture_rate` is quantized hard
/// (327 of 1,083 entries share the value 45, and 86% sit at 45 or above), so any
/// set of bands puts a ~30-45% lump in whichever band contains 45. Phase 4 should
/// weight the hatch pool on `DexEntry.captureRate` directly, where the raw number
/// behaves like a smooth weight, and use this only for the word shown to the
/// player. See DECISIONS.md.
enum Rarity: String, Codable, Sendable, CaseIterable {
    case common
    case uncommon
    case rare
    case epic
    case legendary
    case mythical

    /// User-facing word. Capitalised here rather than at each call site so the
    /// popover and the dex cannot disagree.
    var label: String {
        switch self {
        case .common: "Common"
        case .uncommon: "Uncommon"
        case .rare: "Rare"
        case .epic: "Epic"
        case .legendary: "Legendary"
        case .mythical: "Mythical"
        }
    }
}

/// A collectible. One per base species plus one per regional form: 1,083 total.
///
/// `id` is PokeAPI's `pokemon.id`, which is the National Dex number for base
/// species (1...1025) and a synthetic id at or above 10000 for forms. `speciesID`
/// is the species the entry belongs to, and is where rarity comes from, so a
/// regional form inherits its rarity for free: Alolan Vulpix reports species 37
/// and capture rate 190, exactly like Vulpix, and is exactly as common.
struct DexEntry: Codable, Sendable, Identifiable, Hashable {
    let id: Int
    let speciesID: Int
    /// PokeAPI slug, e.g. `vulpix-alola`. Stable, and the cache key's basis.
    let slug: String
    /// User-facing name, e.g. "Alolan Vulpix". Taken from PokeAPI's English
    /// species name at generation time rather than title-cased off the slug,
    /// because title-casing gets `farfetchd`, `mr-mime` and `nidoran-f` wrong.
    let name: String
    /// `alola`, `galar`, `hisui`, `paldea`, or nil for a base species.
    let region: String?
    let generation: Int
    let captureRate: Int
    let legendary: Bool
    let mythical: Bool
    let spriteSet: SpriteSet
    /// Whether this entry has a shiny sprite in its resolved set. True for 1,081
    /// of 1,083, so the two exceptions must not render as a blank tile.
    let shiny: Bool
    let animated: Bool
    let rarity: Rarity
    /// Evolution targets, deduped, restricted to ids that are themselves in the
    /// pool. Usually 0 or 1; Pikachu has two (Raichu and Alolan Raichu), which is
    /// real branching regional content that falls out of the data for free.
    let evolvesTo: [Int]

    var isRegionalForm: Bool { region != nil }
}

/// The bundled manifest, as generated by `scripts/generate-dex.py`.
struct DexManifest: Codable, Sendable {
    let version: Int
    /// The sprites repo commit every sprite URL is pinned to.
    ///
    /// Load-bearing, not decorative. `raw.githubusercontent.com` serves sprites
    /// with `cache-control: max-age=300`, so a branch-tracking URL would have the
    /// disk cache revalidating every five minutes. Pinning a commit makes each
    /// URL immutable, which is what lets a cached sprite be trusted forever and
    /// read with no network at all.
    let spritesCommit: String
    let maxSpeciesID: Int
    let entries: [DexEntry]
}
